DROP TABLE WEB_MEMBER;

CREATE TABLE WEB_MEMBER
(
	ID			VARCHAR2(20) PRIMARY KEY,
	PASSWORD	VARCHAR2(20) NOT NULL,
	NAME		VARCHAR2(20) NOT NULL
);

INSERT INTO WEB_MEMBER VALUES ('admin','admin','관리자');

COMMIT

SELECT * FROM WEB_MEMBER;